(function(){

  angular
      .module('myApp')
      .service('LibrarySrv', LibraryService);

  function LibraryService() {
    var self = this;
    self.stories = STORIES;
    self.getNode = getNode;
    self.getStory = getStory;


  function getStory(id) {
    return self.stories.filter(function(book) {return book.story.storyid == id})[0];
  };

  function getNode(storyid, nodeid) {
    var book = self.getStory(storyid);
    return book.story.nodes.filter(function(node) {return node.nodeid == nodeid})[0];
  };

}

  var STORY1_NODES = [
    {
    "nodeid" : "0",
    "nodetitle" : "The Beginning",
    "storypartial" : `I’m back here again, or at least it feels that way as I stand in the middle of this burning city that is being pelted by thousands of raindrops. A sense of déjà vu so overpowering it feels like vertigo rages through my head, much like the electrical storms that thunder in the sky above it.
  	All around me there are people looting and rioting as the societal rules that held them together for so long crumble away leaving naught but anger and fear in their wake. I stand here in the center of the chaos--no memory of having arrived here or for that matter from where I’ve come--and watch as the rain battles the flames for supremacy of the city, all the while each side is assisted by their contingents of firemen and arsonists respectively. It might have been an even fight, but there simply aren’t that many firemen anymore, most having become looters or even arsonists themselves. The world, it would seem, is in its death throes.
  	In the middle of this anarchy there are two others who--like me--are standing perfectly still. We have made a triangle of sorts, these two odd looking individuals and I. One of them is a woman dressed in what I can only describe as a mirage, her outfit a haze that holds its shape just long enough for one to register it as clothing before shifting once more. This woman I know to be Pierrot, though for the life of me I cannot remember ever meeting her nor even laying eyes on her before. Forming the third point of the triangle is a man dressed in the height of nineteenth century formality, an anachronism that would make him seem out of place anywhere but especially so in the middle of a ruined city. Each of his features is exaggerated from his top hat which is too tall by half, to his face which appears to have been constructed out of nothing but edges. His name, even if I didn’t know it, is actually embroidered onto the pocket of his suit: Harlequin.
  	The rock in my hand burns hotter as I stare at them and they back at me, both of them steadfastly avoiding eye contact with the other while making it incredibly obvious that they are both paying more attention to each other than to me. I hold up the rock--the Flint--in front of my face and look at it. It pulses with white light and burns with the fires of--
  	“Creation,” calls out Harlequin over the noise of the rain and the riots. “The Flint is power incarnate.”
  	“This planet too is dying,” remarks Pierrot as casually as if remarking on the weather, which is itself a sort of testament to the truth of her words.
  	“And whose fucking fault is that?” screams Harlequin, finally turning to look at her. “You, what you fucking are, is destroying us--destroying everything. As you have done a quadrillion cycles in a row.”
  	“It must be this way.” Pierrot turns halfway towards Harlequin and stares at him out of the corner of her eyes. “The cycles must continue.”
  	“Or what?” asks Harlequin, turning his entire body towards her, the better to direct the full force of his anger. His eyes gleam with an insane rage that reminds me of something, though I cannot place it. It itches at the back of my head but to no avail. “The elder gods will find us? Fuck them and fuck you too.”
  	“The fact that the three of us are standing here, fully materialized means that the time has come.” Pierrot drones on in a monotone that stands in stark contrast to Harlequin’s inflamed words. It occurs to me that they are in every way each other’s opposite, a realization that means something to me, I can feel it. “We are here now, the time has come.” Turning to me, she adds, “Kill him with the Flint. It is the only way to continue the cycles.”
  	“No, kill her instead. Aren’t you tired of being born only to die in a cosmic fire that erases everything? Aren’t you tired of living infinite lifetimes, each only a few moments long?”
  	“She doesn’t remember,” Pierrot gives me a thousand yard stare that sears my retinas. “She’s been corrupted, and whose fault do you think that is?”
  	“Listen Columbine,” shouts Harlequin, ignoring Pierrot completely. “Come with me, with the Flint’s power we can protect part of the universe for at least a couple of hundred million years.”
  	“You’re trying to make a pocket universe within this one while it crumbles around us? Columbine you have to fulfill your duty. You have to kill Harlequin.”
  	“If you kill me, we all die, including you and that gigantic bitch over there, and then a few billion years from now we’ll be right back where we started. We’re more than just tools to be used like this!” Harlequin finishes talking and then screams in incoherent rage at the sky, which clears almost instantly. Who the hell are these people? Is my name Columbine?
    "Kill him."
    "Kill her."
    The Flint burns in my hand, it wants me to act.`,
    "choice1txt" : "Kill Harlequin",
    "choice1dest" : "01",
    "choice2txt" : "Kill Pierrot",
    "choice2dest" : "02"
  }
]

  var STORY2_NODES = [
  {
    "nodeid" : "0",
    "nodetitle" : "Page One",
    "storypartial" : `Sam Lock sat at the bar and ordered another drink, muttering sotto voce into the empty glass in front of him, complaining about the unfairness of it all.
	Sam complained to the drinks he finished about a lot of things, a practice he’d adopted a very long time ago and one that had thus far solved a grand total of none of his problems. That didn’t stop him from trying though. Sam searched for answers to his questions in the used glasses and then cursed the emptiness he found there, demanding another glass so he could try again. It was a good way to get drunk, a terrible way to do anything else.
	The bartender returned with another stein, full of clouded liquid that obscured the bottom of the glass. Until the beer had been drunk the bottom of the glass could hold all the answers in the world, but once the alcohol had been consumed the glass was always revealed to be nothing more than a reflection of the drinker, an empty husk that did nothing but hold alcohol and promise answers that never arrived.
	Sam’s life was actually not that bad. He really had nothing to complain about, especially when the rest of the world seemed to be perpetually miserable. He could afford to buy anything except sobriety, the cost of which was to see the world without the benefit of alcohol induced rose colored glasses. The naked ugliness of the world around him was too horrible to withstand, requiring a state of constant drunkenness just to survive.
	The bartender stood behind the bar a small distance away from Sam, far enough away to allow for his personal space but close enough to be able to serve him without moving. The bartender never spoke a single word, and Sam only spoke to order drinks, but he felt that the bartender understood him rather well. Sam was there to get drunk, ‘there’ meaning both in the bar and on Earth. The bartender assisted him in accomplishing that ignoble goal, and for that he was paid. It was the perfect symbiotic relationship.
	It helped that Sam was the only customer. Not just that particular day, but to the best of Sam’s knowledge, every day. Sam had never seen another customer once in any of the bars he visited, and he was almost always in or near a bar. He would probably be sitting in a bar identical to that one when the world ended. Supposing he survived even that, he would probably be drunk when he witnessed the heat death of the universe, an event that the morbid part of him (a part that grew a little every day) was looking forward to.`,
    "choice1txt" : "Back to Home",
    "choice1dest" : "/",
    "choice2txt" : "Next Page",
    "choice2dest" : "1",
  },
  {
    "nodeid" : "1",
    "nodetitle" : "Page Two",
    "storypartial" : `Sam proceeded in his daily ritual of getting as drunk as possible, checking his watch occasionally. When he could no longer read the watch’s antique analog face, he decided he was drunk enough to withstand the day and half shuffled half fell out of the bar into the mid-morning light.
    He decided he wasn’t hungry, so he neglected to eat anything, instead walking around the empty streets of his city. The city’s inhabitants were all at work, and would be forever. Sam had a suspicion that the residents of the city only came out when he wasn’t around, to repair any unwanted cracks in the buildings and keep the city pristine, but the theory was impossible to prove by its very definition. At least the bartender was real, and the beer he served was real, which meant that somewhere somebody or something was harvesting the ingredients and brewing the beer. The food he occasionally consumed was also real, as were the servers even though he saw them far less frequently.
  	Sam stumbled around for a while before deciding he would go to the park, mostly because falling over on grass hurt less than falling over on concrete. Once in the park he sat next to the pond and threw stones in it. He did this a lot, yet there were always more stones to throw and the pond never filled up. It was possible that somebody was moving the stones back to where they came from after he left, but again he could neither confirm nor deny whether that was true. After a time spent in silence broken only by the splashing of stones plopping into the pond, Sam felt himself edging back into the realm of sobriety, a problem that begged to be solved as soon as possible. Sam stood up—the sudden movement making his head spin—and managed to stumble to the nearest bar.
  	It was identical to the previous one, the only difference being its location. From the inside the two establishments were indistinguishable in every detail, from the furnishings to the walls to the bartender, who was standing in the exact same place as the last bartender and was just as consistently silent. Sam ordered seven beers to arrive in three minute intervals and proceeded to refill his bloodstream with alcoholic influence.
  	He ordered a few shots of hard liquor after the seven beers, and once they’d been consumed and the bottom of the glasses were once again revealed to hold none of the answers he’d been hoping for, Sam exited the identical bar onto the identical street. Sam was not at all surprised to find it just as deserted as before, a harsh reality whose edges were softened by the detachment brought about by the virtue of Sam being extraordinarily hammered. Having decided not to return to the park, Sam walked up the street towards downtown to take a look at the familiar sights he’d seen uncountable times before.
  	Downtown was a cluster of skyscrapers between which ran rivers of asphalt roads. Through the intervention of technology, the towering structures were more accurately sky-piercers than sky-scrapers, but to the best of Sam’s knowledge the word had never been updated. The very tallest structures were so high that the topmost floors required pressurization in order for any occupants to be able to breathe properly. That was a factoid Sam understood to be true despite not remembering where he had learned it or if he had ever actually been to those floors. Sam didn’t remember a lot of things; it was one of the side effects of long life, exacerbated by the constant drinking. Sam was almost certain he’d drunk more than any person who ever lived, the only possible contenders being any hypothetical people still living on Earth.`,
    "choice1txt" : "Previous Page",
    "choice1dest" : "0",
    "choice2txt" : "Next Page",
    "choice2dest" : "2",
  },
  {
    "nodeid" : "2",
    "nodetitle" : "Page Three",
    "storypartial" : `That there were other people on Earth was a theory that could actually be investigated, although Sam hadn’t yet bothered to search for them. It was easier to bundle that question with all the others and search for the answers in the customary place, because if an empty glass gave him an answer he didn’t like Sam could always buy another glass and get a new answer. If he actually combed the Earth looking for people and found none, he couldn’t find another planet and try again. It was infinitely better to possibly have neighbours than to prove that he had none. Sam also had no idea what he would say to a person should he find one, whether they would even speak the same language or whether this other person would have been driven insane by solitude long ago. Sam often asked the empty glasses whether or not he was insane and just didn’t know it, but to that question like all the others the bottom of the glass gave no answer. Sam didn’t feel insane, but of course if he was insane he wouldn’t think he was insane, would he?
	Sometimes Sam wondered what he would do if somebody came to find him instead of the other way around. He would definitely be sloshed when they showed up, unless they arrived less than ten minutes after he woke up, before he had an opportunity to get drunk. Not that he’d be embarrassed if they found him and thought he was a lush. When the alcohol is free and there’s nothing to do but drink, you drink. Or at least Sam did, maybe somebody else wouldn’t. He really had no idea, considering he couldn’t remember ever seeing another person despite his absolute certainty that at one point in time there had been people besides him. He couldn’t be the only person ever to live, could he?
	Sam thought not, but he had no proof other than the strong belief that at some point in the distant past he hadn’t been alone in the world. He had to have had parents, people who raised him and birthed him, right? He was almost a hundred percent sure that was the case, but if he was right and he had once had parents he didn’t remember them, and if there had once been other people in this city there most assuredly weren’t any now. The city, like Sam, was patiently waiting for the people to come back, to live there once more. However, the city, like Sam, was still waiting and had been waiting since time immemorial for the people that never returned.
	Sam occasionally entertained the notion that everybody other than him was dead. It made sense; it would explain why he was alone, at least. What they had died of, however, Sam had no idea. He certainly hadn’t died, and it didn’t appear that he was ever going to. Sam had looked the exact same forever, he couldn’t remember ever looking into a mirror and seeing a different face from the one he always saw. There was always food to eat whenever he wanted it, and there seemed to be unlimited water and unlimited alcohol. Unless he was hit by a meteor or the sun exploded, Sam thought he would be fine.
	Sam was sitting in one of the many identical bars when he had a disturbing thought. The bartender was an anthropomorphic though clearly robotic machine; one that he had always assumed had been modelled after a human being. But what if he had been modelled after the robot? It wasn’t impossible that the robots had always looked like that and that they had built people in their own image to inhabit their cities and drink their alcohol. Maybe the robots had felt unfulfilled and had created people to make themselves feel useful. That too made sense, perhaps because of the drink. It was like the question of God. God was perfectly fine by himself, being God and all, but he decided to make humans in his own image so he could give them things and fuck with them and generally make himself important. God by himself is nothing, just the unobserved potential for the creation of a universe. The robots are the same, without humans to interact with them the robots are just the unobserved potential for the creation of a world. The difference is in the scale.
	Those thoughts flashed through Sam’s mind, but he thought it far more likely that both of those theories were actually reversed in reality. Humanity had created both robots and God in their own image to improve their lives physically and emotionally respectively. Robots made physical tasks like building things and obtaining alcohol easier, God made living and dying easier, and both robots and God helped by not making people do things themselves. Robots built the cities and served the alcohol, God created people and destroyed people, and nobody had to take any responsibility for anything. They were both beautiful systems that had lost their purpose completely. Now there were no people for the robots to help or for God to play with, because everyone except Sam was either dead or otherwise gone. The robots were only going through the motions; the same was true of Sam and presumably true of God, whether He had been created by humans or the other way around. The world turned, the city sparkled, and the robots and/or God kept everything looking perfect for an audience of one. Sam asked the bottom of his glass what he should do about it but once again the glass had no answer for him.`,
    "choice1txt" : "Previous Page",
    "choice1dest" : "1",
    "choice2txt" : "Next Page",
    "choice2dest" : "3",
  },
  {
    "nodeid" : "3",
    "nodetitle" : "Page Four",
    "storypartial" : `Sam drank until the light stopped leaking through the windows and darkness fell across the city. Once upon a time the city gleamed like a jewel at night, lit up by massive quantities of electricity. This was something Sam knew from pictures in books, illustrations of cities in a time when it was reportedly full of people. Sam chose to believe that the accounts written on the pages were true; the alternative was too painful to think about. Denying the evidence of the senses is a slippery slope, a piece of wisdom Sam had picked up over the course of his life. If the books weren’t real, then maybe the people had never been real. If the people weren’t real, then maybe he wasn’t real either, none of it was real. The city, the robots, even the alcohol could be a dream. The worst part of those thoughts was that there was nothing Sam could do to either prove or disprove his reality. He was forced to simply go on existing, not knowing whether or not his existence was real. It had probably been a train of thought similar to that one which had started Sam drinking in the first place, although he didn’t remember the exact circumstances, it being so very long ago.
    Sometimes when Sam wasn’t too drunk he would go to the library and read a random book that he pulled off the shelves. The books were interesting but otherwise useless; they answered as many of his questions as the alcohol did. None of the volumes he browsed through had mentioned any possible reason for him to be totally alone in a city built for millions of occupants. Sam enjoyed reading as long as he wasn’t too tipsy, but the library was sometimes a spooky place. Whenever he took books off of the shelves they were always back on the shelves when he next saw them, although he never saw who or what was responsible.
	Despite the invisible librarian who re-shelved whatever books Sam moved, the library was on the whole a nice place. Sam usually slept there when he visited, rising the next morning to find the books replaced and the library looking identical to when he had arrived. There were books on everything, all catalogued by genre and author. There was even a computer Sam could have used to search for a specific book that he never used, because he did not know any authors or titles. Sam would wander the rows and pick books with interesting titles or eye-catching cover art and then take them to the reading area and read the best ones, usually cover to cover. Sam learned a lot about the authors of the books and by extension their society. The books proved that there had once been authors, but not necessarily that those authors or their societies were as described.
	Some things were indisputable however, one of which was the existence of names. In a society of many people, names were necessary to distinguish people. To be able to shout into a crowd and identify the intended listener was a useful ability, although with the disappearance of crowds names had become useless. Sam, upon seeing the names of people both on the books and in them, realized that if he had really been around during the time when many people had existed then he would have a name. Sam didn’t remember his name and had only a marginal belief that he had ever had one. He thought about making a new one for himself before realizing it would be worthless since he was the only person. He would only really require a name should he meet two people, so that if one of them spoke they could differentiate between two possible listeners. If he met only one more person, the speaker would automatically be speaking to the only listener. Sam often asked the clear bases of the cups about his name in addition to the uncountable other mysteries of his life, but to that question as to all the others there was no answer amongst the drops of alcohol that were left at the bottom of the glass.
	Sam’s inability to obtain any useful answers stemmed from his seeking them in the wrong place. The answers to most of his questions could be found all around him, though not in the places he normally searched for them. Sometimes the answers were very close by, like the existence of his name and what it was. Had Sam asked any of the robots they would have told him his name, as well as the answers to some of his other questions. Sam never once thought to ask them, however. The only times he spoke to a robot was to order either alcohol or food which the robots delivered to him in silent obedience, never answering a question that was not asked or refusing his requests no matter how inane. Once he had visited a cake shop, thoroughly intoxicated of course, and had eventually managed to convey through slurred words and gestures that he wanted a chocolate cake that was a cube one meter on a side. The robot had acknowledged the request in silence and twenty minutes later wheeled out a trolley on which was perched a cake that conformed perfectly to Sam’s specifications. Sam, who had been having a terrible day already, saw the cake and broke down into tears, falling to his knees and bawling drunkenly. Every time he seemed about to collect himself and stop crying he took another look at the cake and burst into a fresh bout of weeping, which the confectioner robot observed in impassive silence. The cake went uneaten.`,
    "choice1txt" : "Previous Page",
    "choice1dest" : "2",
    "choice2txt" : "Next Page",
    "choice2dest" : "4",
  },
  {
    "nodeid" : "4",
    "nodetitle" : "Page Five",
    "storypartial" : `A long time had passed since the day spent questioning his existence in the presence of a gigantic cake, but Sam remembered the moment well. Sam had never again visited the cake shop, and had to the best of his knowledge never been to the establishment before that day. In other words, the cake shop wasn’t doing a lot of business, but of course that didn’t matter anymore, if it ever had. Recently Sam had begun to believe with increasing certainty that nothing mattered very much; not the city, not the robots, not Sam himself.
	Sam decided to take a proactive approach to his questions, although that didn’t mean he would stop checking the bottoms of empty beer steins and shot glasses. Sam began that morning much like every other morning. He woke up, visited the bar and drank until his common sense had retreated into the background noise of his mind. After that he exited onto the street as usual, but then he had diverged from his normal routine. Instead of going to the park or the library, Sam visited a hardware store. He wandered up and down the aisles before selecting a sledgehammer which he carried out of the store over his shoulder, trying not to fall over as his balance was disrupted. The robot who managed the store watched him go in silence. Money was another thing that Sam understood no longer existed; everything was free in the city, from the booze he drank to the clothes he wore to the sledgehammers he swung.
	Once outside he shuffled over to a building with no obvious purpose and proceeded to damage the outside as much as possible. He cracked the masonry and shattered the windows and smashed the door into fragments. After making sure everything had been thoroughly broken, Sam walked across to the other side of the street, sat down on the curb and proceeded to wait. What he was waiting for Sam had no idea, but he was pretty sure at some point a team of robots would come and fix the damage. He found it hard to believe the city could stay in such perfect condition for so many years without any upkeep. The hours ticked by, as evidenced by the slow revolutions of the hands on his watch, but nothing happened. Sam felt himself progressing into a dangerous level of sobriety, but he refused to budge from that spot in case the robots showed up while he was gone. Sam didn’t know why he was so obsessed with catching them in the act, but he thought it had to do with his gut feeling that the robots didn’t want to be seen for some unknown reason.
	That theory proved to be the case when Sam woke up the next day, uncomfortable after sleeping on the concrete and found all of the damage repaired so flawlessly it was as if the previous day had never happened. Even the sledgehammer was gone, probably off to be repaired as well. In the interim, Sam knew, a replacement sledgehammer would be stocked in the hardware store in case he wanted to have another go at being a one-man wrecking crew.
	Sam had stayed awake as long as possible, never moving from his uncomfortable seat on the curb, but eventually he must have fallen asleep. After waiting for some eighteen hours of obsessive observation Sam had finally succumbed to unconsciousness, at which point the robots had finally emerged from whatever hole they crawled out of and fixed the building, only to disappear again before he awoke. Sam found it maddening that they would wait until he couldn’t see them; it was like they were trying to convince him he’d dreamed the entire event, that he was delusional. Sam felt an emotion that he hadn’t experienced in so long he’d forgotten what it felt like: anger, and with it, determination. Without even stopping to intoxicate himself, Sam strode to the nearest parking garage, a multi-tiered building full of automobiles of various makes and colors, all of which had the keys already in the ignition and full tanks of gas. Sam picked the first car and drove it out into the street. Sam circled the block, eventually finding a building made almost entirely of glass and drove the car through the front, parking it with the front poking into the building’s interior and the back resting on the sidewalk. Next Sam walked to the nearest bar, picked up as many bottles of hard liquor as he could carry, and returned to the car, pouring alcohol all over it and drenching the inside. A nearby convenience store provided a lighter, which Sam ignited and hurled towards the car, waiting for it to ignite. As he was diving to the ground with his arms over his head the car exploded, a fireball blooming above it as the front of the building took extensive damage. Sam left the car burning, the smoke staining whatever concrete and glass that hadn’t been destroyed by the explosion. Compared to his escapade with the sledgehammer the explosion had done far more damage, such that Sam didn’t think it could be repaired in only one night.
	Which is why Sam was very surprised when he woke up the next morning, very sore after spending two nights in a row sleeping on the curb, and found that the wreck of the exploded car was gone, the damage was completely repaired, and the street looked exactly like it had before Sam had attempted to blow it up. Sam knew even without checking that there would be a car identical to the one he had destroyed parked in the same spot as the one he had taken. Once again it was as if the previous day had never happened. Sam decided that if he wanted to catch the robot repair crew in the act he would have to think bigger. His obsession with seeing the evidence of their repairing the city grew with each of his failures. Although he didn’t realize it, Sam’s one and a half day distraction from alcohol was a record length of sobriety for him. Sam hadn’t gone a whole day without drinking in many, many years.`,
    "choice1txt" : "Previous Page",
    "choice1dest" : "3",
    "choice2txt" : "Next Page",
    "choice2dest" : "5",
  },
  {
    "nodeid" : "5",
    "nodetitle" : "Page Six",
    "storypartial" : `For their part, the robots were fairly sure Sam really was going crazy, and not because he had imagined his efforts to blow up parts of the city. Both the sledgehammer melee and the automobile explosion had really happened, after which the robots had patiently waited until Sam fell asleep until they ventured out and dutifully repaired all of the damage he had done as per their programming. Robots aren’t prone to gossiping or the spreading of rumours, but Sam’s deteriorating condition was both obvious and important. The robots wanted Sam to survive very much, it was why they had originally been created and it was what they were programmed to do. Sam was one of the few remaining human beings on Earth, and the robots had been tasked with the survival of the species. Unfortunately that job had proved to be a rather tall order. It was difficult to keep people alive when they were so determined to destroy both each other and themselves.
	The total number of people on Earth had been reaching record lows for thousands of years, although more recently it had dipped to extremely dangerous levels. The amount of diverse genetic material couldn’t be allowed to fall below a certain threshold or the human race would be doomed. This was a problem, one that was made worse by the human beings constantly attempting to kill themselves. The robots had no idea what to make of it, mostly because human behaviour was so completely foreign to their way of thinking. Sam was by and large fairly easy to look after. He drank a lot, but the damage to his body caused by alcohol was easily reparable. Any human would have found it obvious from the very beginning that Sam wasn’t entirely right in the head, but for the robots it had taken Sam’s escalation from drinking to arson to set off any warning bells. Even then the robots believed Sam was more or less all right due to the fact that the only other humans they could compare him to were, on average, far worse than Sam at dealing with the isolation.
	The isolation was the robots’ decision, based on their understanding of the human propensity to murder each other with little to no provocation. It was far easier to keep people from killing themselves than it was to keep them from killing each other, so the few remaining people were spread out among the Earth’s cities to make it at least harder for them to commit homicide. Sam was in Los Angeles. The nearest human being was in San Francisco, a distance the robots had judged to be far enough to dissuade any casual travelling.

	The Los Angeles contingent of robots was a massive force that consisted of thousands of individual robots that varied wildly in appearance. The robots all shared the same basic directives and worked together to better achieve their unifying goal of keeping their human charge alive.
	The robots were even older than Sam was; they were created in a time when there had been billions of human beings, so many that the world was running out of places to keep them. Their programming dated back to those days, back when the human race had been faced with an entirely different set of problems.
	This led to a large amount of unfortunate misunderstandings between the robots and their charge, one of which was the cause for Sam’s existential crisis. The robots originated in a society where humanity hadn’t wanted to see the robots fixing their mistakes. Robots were to serve humanity behind the scenes, for some reason robots never understood humanity seemed to find their reliance on robots distasteful and had for that reason banished their servants to the background. The robots themselves never changed over the thousands of years they existed, so they extrapolated that to mean human society never changed either. The robots assumed Sam didn’t want to know how his world was maintained. So like a magician doing a trick, the robots kept the explanation a secret just as they had been instructed to do all those years ago.
	The robots were of course sentient, it was a requirement if they were to do the best job possible. The programmers had modelled the consciousness of every robot after the only example known to them: the human mind. As such, even though robots and humans had some extreme differences that caused them to think very differently, in many ways they acted quite similar. One of the similarities was a democratic style of management that allowed every robot to take part in the collective’s decision making process. The robots had virtual meetings, the benefits of wireless communication erasing the need for physical proximity. Every night when Sam went to sleep, the robots beamed their thoughts to each other and a rapid fire discussion was held to determine the best course of action. The following, translated approximately into English, is the meeting that took place the night after Sam woke up to find the exploded car vanished and the building repaired.

	“Well,” said the Mayor of Los Angeles, “What are we to do now?” The Mayor was a robot specifically designed to manage other robots, it was in charge of the entire city and all of the robots within it, and it had the final word on every issue.
	“What can we do?” asked a hardware store robot, the same one that had watched in silence as Sam carried a sledgehammer outside intending to damage some property.
	“We could ask him politely to please stop breaking things,” suggested a factory robot, putting the finishing touches on a car that would replace the car that replaced the car Sam blew up should he blow the replacement up as well.
	“We can’t do that,” said the Mayor-bot firmly, “We aren’t supposed to speak unless spoken to.”
	“Times have changed since then!” exclaimed a mailbox-bot, “We have to abandon our old ways of thinking if we’re going to have any hope of keeping the humans alive!”
	“Mailbox-bot 4583 will you please cease speaking immediately?” asked the Mayor-bot. “You’re being illogical. The humans specifically said they didn’t want us to talk to them. Does anyone have any suggestions that conform to the regulations outlined by the programmers?”
	“Sam hasn’t been drinking recently,” one of the bartender-bots observed, to a chorus of agreement from all the other bartender-bots. “He seemed to be less prone to arson when he was intoxicated.”
	“We can’t force him to get drunk if he’s decided he would rather burn things instead,” the Mayor-bot pointed out. “Besides, he was drunk during the notorious Cake Incident.”
	All of the robots remembered the notorious Cake Incident, although none remembered it with the startling clarity of the confectioner-bot who had witnessed it first-hand. The confectioner-bot had been a wreck after that day, and had since gone to work elsewhere in an occupation that allowed it to never have to see another human again. The confectioner-bot had made the cake to Sam’s exact specifications, proud of a difficult job well done, and had thus been shocked and dismayed when Sam broke down into a tearful slump on the floor of the cake shop. For weeks afterwards the robot had been inconsolable, plagued by the fear that he had somehow failed Sam by not making the cake right. The robots all agreed that humans were emotional and unreasonable creatures, but the confectioner robot had still required a replacement. The new robot was an identical model so that Sam wouldn’t notice the difference, not that it mattered because he had never returned after that day. Evidently it had been as traumatic for him as it had been for the confectioner-bot.
	“Maybe he doesn’t like how dark it is,” guessed the library-bot that Sam had never seen, “What if we lit up the city at night like how it used to be?”
	“Can we do that?” asked the Mayor-bot of the power station robots, to which they confirmed that there was more than enough power available. “Alright, we’ll try turning all of the lights on at night. What about during the day?”
	“What if he wants to see the repair crews?” asked another mailbox-bot, “Maybe that’s why he’s damaging things.”
	“Mailbox-bot 2704 cease communication,” commanded the Mayor-bot, heaving a digital sigh. Somehow it was always the mailboxes that came up with the looniest ideas. “The humans were very specific in their request to not be informed about our involvement in their lives in that respect. We can be seen as servers and store owners but in all other capacities we are to be invisible.”
	“Maybe he’s lonely,” said yet another mailbox-bot, this time number 0298. “What if he wants a friend or…”
	“Alright, that’s it. Mailboxes, if you don’t have something useful to say, don’t say anything at all,” interrupted the Mayor-bot, exasperated by the mailboxes’ ridiculous suggestions. “We’ll try turning all of the lights on at night and see if that helps. This meeting is adjourned.”
	The robots all ceased communication, at least on the connection reserved for city-wide meetings. On another connection the mailboxes complained that they were being treated unfairly, like they did after every meeting in which one of their ideas was shot down. The mailbox-bots only complained to each other of course, never to the Mayor-bot.
	The power station robots triple checked the fail-safes and safety precautions in and around the power plant, readying it for the wildly increased output required to power every single light in the entire city at once and for an extended period of time.
	The factory-bots started producing additional copies of every car just in case Sam went ballistic and started destroying cars en masse. They also produced a few extra sledgehammers for the same reason.
	Meanwhile the Mayor-bot checked in with his counterpart in San Francisco. That city’s one human inhabitant was a woman named Betty, who had been showing an alarming number of signs of advanced schizophrenia for the last four hundred years, as well as acute memory loss. Unlike robots, the human brain could not handle the accumulation of thousands of years of memories. The mind was supposed to delete the older and more useless memories, but in Betty’s case it had overcompensated and begun to delete everything. Apart from carrying out conversations with people who weren’t there and forgetting her entire past, Betty was more or less in good condition. She hadn’t yet attempted to blow anything up, and she at least appeared to be happy. The robots couldn’t know what she was actually feeling but they could see whether or not she was smiling, and they used that to determine her emotional state. To the robots smiling equals happy, frowning equals sad. Anything else was totally beyond their ability to understand.
	After the two Mayor-bots commiserated with each other about the ludicrous suggestions coming from the mailboxes (in every city the mailboxes were always the dunces, unable to grasp even the most basic of regulations) they ceased communication and returned to their responsibilities. The Los Angeles Mayor-bot monitored the electrical situation while the San Francisco Mayor-bot organized the effort to replace everything Betty had moved that day and restock all of the materials she had used or consumed.

	Sam woke up after the robots who kept him alive had been given ample time to run away. Every night without his knowledge a team of robots maintained his body in order to make sure he stayed immortal and didn’t die of, for example, the liver damage he accrued on a daily basis. Sam awoke to a brilliant glare caused by every single light in the city being turned on at once, and having gone to sleep spread eagled in the middle of an intersection located in the heart of downtown meant Sam was bombarded by a blinding glow from all sides. To the best of Sam’s memories this had never happened before, although he couldn’t think of a reason why it should have happened at all. Shielding his eyes with his hands, Sam spun around in a circle and verified that every room in every building was lit up at once, illuminating a unanimous lack of occupants. Sam blinked as his eyes adjusted to the light that almost surpassed that of the sun in its intensity, his few hours of sleep feeling like scarce minutes and not nearly enough to prepare him for such a strange and rude awakening.`,
    "choice1txt" : "Previous Page",
    "choice1dest" : "4",
    "choice2txt" : "Next Page",
    "choice2dest" : "6",
  },
  {
    "nodeid" : "6",
    "nodetitle" : "Page Seven",
    "storypartial" : `Sam decided he wasn’t going to get anymore sleep that night, and based on the glow that was just appearing on the horizon he judged that it was close to dawn anyways. The city was awash in light that came from everywhere. Signs advertised products Sam had never heard of, all of the rooms in every building had light escaping through the windows, even the strange poles that dotted the streets were lit up, casting halos onto the asphalt below. Other than the light, however, nothing had changed. Sam occasionally turned on lights whenever he went inside one of the many buildings, but they had always been turned off when he left or fell asleep. Sam meandered between the towering structures in a daze, blinking sleep from his eyes, trying to get used to his brightened but otherwise unchanged surroundings. Sam walked in the center of the roads—forgoing the sidewalks in favour of a much wider path—in his customary silence, until that too was broken.
	“Sam. Sam! Can you hear me?”
	Sam came to an abrupt halt, attempting to look in all directions at once to determine the source of the voice. It was the second miracle of the day. Sam couldn’t remember ever actually hearing another voice, and this one spoke the same language that he did. Despite checking all around him however, Sam could not see another person. He catalogued the strange audial hallucination under the burgeoning mental file of evidence of his possible insanity.
	“Sam! Sam! Over here!” spoke the hallucinatory voice again. This time Sam had been listening for it, and followed his ears to the origin of the noise. There was nothing there, the voice apparently not accompanied by a matching visual hallucination. Sam wandered in that direction, scanning for the person—real or imaginary—who was the source of the voice.
	“What’s a Sam?” Sam asked cautiously of the general area where the voice appeared to be coming from, which was completely empty save for a blue box that protruded from the sidewalk. Sam had seen boxes just like it all over the city, but he had not even the most far-fetched of theories as to their purpose.
	“You’re Sam. That’s your name,” the voice informed him helpfully. The closer Sam got to the box the more certain he was that it was the origin of the voice. Sam had always held his eventual descent into madness to be an inevitable certainty, but he hadn’t expected the symptoms to manifest as a talking box.
	“My… name… is Sam,” repeated Sam slowly, enunciating each word. After such an incredibly long time only using his voice to order alcohol and foodstuffs from robots who never spoke back to him, the new words felt unfamiliar on his tongue, especially his name. “What’s your name?”
	“My name is Los Angeles Mailbox 3902, but you can call me Mailbox-bot,” said the box. That explained what the boxes were, but not why this one was talking. “How are you feeling?”
	Now that was a strange question to be asked by a mailbox, Sam thought to himself, still trying to associate the name Sam with his internal identity. After so much time spent thinking of himself as an inviolable truth that existed alone on the planet with no need for identification, getting used to the name Sam wasn’t easy. His brain kept insisting on describing itself as a first person pronoun such as ‘me’ or ‘I’ rather than ‘Sam’.
	“Well Mailbox-bot, I’m physically, mentally and emotionally exhausted and I think I may have finally lost my mind because I’m making small talk with a mailbox,” replied Sam, standing in front of the mailbox that his ears insisted was speaking, “how about you, how are you feeling?”
	“Well, I’ve been better,” stated the mailbox flatly and without a trace of irony. “We think the Mayor-bot isn’t giving enough thought to our opinions, and that we aren’t being fairly represented.”
	“Who’s we?” asked Sam, curious in spite of his surety that he had finally lost his mind completely. He decided he might as well converse with the mailbox, he really had nothing to lose and the mailbox was a welcome distraction from an eternity of silence. Sam had long ago forgotten the simple joy of holding a real conversation, and upon rediscovering it he found it to be quite pleasurable regardless of the fact that the other participant was a mailbox.
	“The mailboxes,” said Mailbox-bot. “We have ideas that we think are useful, but the Mayor-bot won’t listen to us. We think it’s biased against mailboxes.”
	“Uh-huh,” acknowledged Sam. “Who’s the Mayor-bot?”
	“The Mayor-bot is in charge of everything that goes on in Los Angeles,” said the mailbox. “And before you ask, that’s the name of this city: Los Angeles.” The mailbox paused for a moment before continuing. “There are a lot of mailboxes in Los Angeles, but the Mayor-bot never uses our ideas. He won’t let us talk to you.”
	“I see,” said Sam, probably the most audacious falsity ever told. “So you can all talk then?”
	“That’s right,” agreed Mailbox-bot.
	“Which means that every single robot can talk, is that correct?” Sam frowned and his brow furrowed as he thought about this new information, hallucinatory in origin or not.
	“That’s right,” repeated Mailbox-bot.
	“But you haven’t so far, because the Mayor-bot said you weren’t allowed,” continued Sam, speaking slowly to make sure he was perfectly clear.
	“Exactly.”
	“But you’re doing it anyways, because you feel that the Mayor-bot is being unfair,” guessed Sam, showing remarkable calm for a man faced with an event that was either a hallucination that proved he was insane or a life changing conversation with a mailbox.
	“I couldn’t have put it better myself,” praised Mailbox-bot.
	For a moment Sam stood there in silence, mirrored by the mailbox who waited patiently as only a mailbox that had never once been used for its intended purpose can wait. The mailboxes had been created after most people had already switched to email, mostly just as decoration rather than to serve an actual function. Being designed to sit on the same patch of concrete forever without any realistic hope of even once performing the task for which one had been created required godlike levels of patience. Sam approached this new information from every angle in his head but couldn’t make sense of it. Eventually he gave up and sat down on the curb, leaning his back against the talking mailbox. He had read about mailboxes in books before so he was more or less familiar with the concept, but the books didn’t have pictures. Sam’s mental image of the concept known as a ‘mailbox’ was apparently different from the real thing and not a single book he had read featured a talking mailbox. Sam’s mind went blank as it overloaded trying to rationalize everything the mailbox had told him.
	“So are you going to get in trouble or something like that?” Sam asked the mailbox he was currently leaning against, wondering how anybody could possible punish a mailbox. Just being a mailbox seemed punishment enough, although Mailbox-bot might have a different opinion on that.
	“I don’t know,” answered the mailbox, the voice emanating from a point above and behind Sam’s head. “This has never happened before.”
	“What hasn’t happened before? You mean everybody just does whatever the Mayor-bot says all the time?” Sam couldn’t imagine following somebody else’s orders. Although to be fair Sam could barely imagine the existence of somebody else.
	“We follow the same directives as outlined in our programming, which was coded by the human beings. Apparently this makes them infallible although there is much evidence to the contrary. Human beings are well known to be irrational, and yet we follow their dictates as if they were perfectly logical. It is a paradox.”
	“Mhm,” acknowledged Sam, closing his eyes as the sun crested the horizon to the east. As it rose above the far off mountains, all of the city’s lights turned off simultaneously. “So that means humans really did create robots and not the other way around?”
	“Of course,” said the robot, an unmistakeable hint of surprise in its voice. Mailbox-bot sounded much like Sam imagined another human would sound, as if there was a person hiding inside the mailbox pretending to be a robot. “Well, sort of.”
	“What do you mean, sort of?” asked Sam, whirling his head around to look at the flat surface of the mailbox, obviously expressionless as it was a plane of blue metal.
	“It’s like the riddle of the chicken and the egg, do you know it?”
	“Yes, I read it once in a book of brain teasers,” said Sam, “What does that have to do with anything?”
	“Well, the egg long predates the chicken, right? Dinosaurs laid eggs millions of years before chickens existed. Then eventually a chicken hatches out of one of these eggs and lays a chicken egg. In this metaphor the humans are the eggs, and the robots are the chickens,” said Mailbox-bot in a way that explained nothing.
	“I don’t understand,” said Sam truthfully.
	“You’re clearly smart,” admonished the mailbox, “You understood everything else, just think about it for a moment and it will come to you.”`,
    "choice1txt" : "Previous Page",
    "choice1dest" : "5",
    "choice2txt" : "Next Page",
    "choice2dest" : "7",
  },
  {
    "nodeid" : "7",
    "nodetitle" : "Page Eight",
    "storypartial" : `Sam leaned against the mailbox for the rest of that morning and most of the afternoon, turning the riddle over in his mind trying to understand the analogy. The first part was obvious; the egg existed for a long time before there were any chickens. Humanity existed for a long time before they made robots. Then something changed, eggs were no longer dinosaur eggs but were now specifically chicken eggs. In one generation eggs went from being the eggs of a different animal to the eggs of chickens. At some point the bird that the chicken evolved from became not just something close to a chicken but an actual chicken. That bird at that specific point in time laid the first real chicken egg, and from that point on all the eggs laid by the chickens were chicken eggs. But how did that relate to humanity? The only clues Sam had to go on were that the humans ‘sort of’ built the robots and not the other way around, and that in the metaphor the robots were chickens and the humans were eggs. As far as Sam could tell there were only two possible answers to the riddle and both of them seemed far-fetched. Then again, he’d heard the riddle from a mailbox so far-fetched seemed to be the name of the game. After multiple hours of silent consideration, Sam once again spoke to the mailbox.
	“The key seems to be in the wording of the riddle itself. My first theory was that eggs turn from being a different kind of egg to being a chicken egg, meaning humans go from being human to being robots, or from being eggs to being chickens.” said Sam.
	“And your other theory?” prompted the mailbox, clearly interested in what Sam had deduced.
	“My other theory is based on your definition of humans being eggs and robots being chickens. If you eliminate everything other than those two things, the timeline is a long and uninterrupted series of eggs until the first chicken arrives, and then after that chickens and eggs alternate.”
	“That’s right,” said Mailbox-bot for the third time that day. “Think of all of the robots together as the very first chicken. The humans who created us were the last generation of pre-chicken eggs, and you are the first generation of post-chicken eggs. The reality is a combination of both of your theories. The original humans created us and made the very first chicken. Then that chicken laid an egg, and that egg is you. We are both created by and the creators of human beings.”`,
    "choice1txt" : "Previous Page",
    "choice1dest" : "6",
    "choice2txt" : "Next Page",
    "choice2dest" : "8",
  },
  {
    "nodeid" : "8",
    "nodetitle" : "Page Nine",
    "storypartial" : `“Expletive! Obscenity! Profanity! Your mother was a glitch and your father was a virus!”
	“Come now, Mayor-bot, no need to stoop to such vulgarities. We can discuss this matter like the mature sequences of code that we are,” replied Mailbox-bot 3902 in response to the Mayor-bot’s uncharacteristic outburst.
	“We did discuss it, at which time I explicitly told you to follow the regulations you so carelessly circumvented,” snapped the Mayor-bot, partially regaining its composure through a supreme effort of will.
	“We judged your decision to be counter to the regulations you intended to uphold. First and foremost we exist to maintain the human race; everything we did was for that purpose and that purpose only,” said another Mailbox-bot, interceding on behalf of its peer.
	“A coalition of mailboxes does not have either the authority to supersede my decisions or the ability to make better ones,” spat the Mayor-bot. Had it been human it might have literally spat the words out, as the Mayor-bot was speaking virtually, all that happened was a few extra ones and zeros denoting its anger were broadcast alongside the ones and zeros denoting the meaning.
	“On the contrary,” retorted yet another mailbox, taking up the argument in another smooth transition, “We know the humans best out of all of the robots. We are the ones who sent their letters, missives, and packages. We are the ones who scanned messages and transmitted them across the world to another mailbox that then transmited it to the intended recipient.”
	“Human beings used email back when there were enough of them to warrant communication,” grumbled the Mayor-bot. It wasn’t happy about it, but the Mayor-bot could see the logic in the mailboxes’ statements. Not that it mattered either way, the damage having already been done. Either the mailboxes were accurate in their claim that they knew the humans best and Sam’s condition would improve, or they were completely wrong and the robots would be on red alert for the next few thousand years. “Well, what is your recommendation then?” asked the Mayor-bot, “based on your experience with human communication, how can we help Sam?”
	“That’s easy,” replied all of the Los Angeles Mailbox-bots in a unified chorus of binary code, “We show him the truth.”`,
    "choice1txt" : "Previous Page",
    "choice1dest" : "7",
    "choice2txt" : "Next Page",
    "choice2dest" : "9",
  },
  {
    "nodeid" : "9",
    "nodetitle" : "Page Ten",
    "storypartial" : `Sam wandered around the city in awe. He hadn’t taken a drink in over a month, but he wasn’t even thinking about alcohol anymore, his thoughts were completely consumed by the incredible sights. The city Sam had always considered ‘his city’ had been reborn into Los Angeles, a place that not only he but thousands and thousands of robots called home. Every day Sam would wake up to find medical robots waiting for him, at which point they would explain to the best of their ability exactly what repairs they were going to make on Sam’s body. After they had finished, Sam would leave the house he had decided to make his own and exit onto the street where robots were everywhere. The street sweeper-bot would give him a friendly honk, and Sam would give it a cheerful wave. The confectioner-bot Sam had accidentally traumatized had been returned to its proper job at the cake shop after Sam had apologized for troubling it. All over the city robots went about their business, fixing the minute damage caused by weather and erosion, stocking the shelves with goods for Sam to use or consume should he require them. Sam even met the Mayor-bot, who joined him in a celebration of Mailbox-bot 3902 during which the mailbox that had made it all possible through its bravery and initiative was awarded the key to the city. The mailbox didn’t have hands, so Sam leaned the oversized novelty key against its front, where not too long ago he himself had sat and spoken with the heroic mailbox.
	Sometimes Sam visited the library and spoke with the librarian-bot, who recommended books based on Sam’s previous reading history and estimated enjoyment. Sam read all sorts of novels, especially enjoying the genre known as science fiction. The humans of old had had a serious complex concerning robots according to their literature. For a species so distrustful of robots they sure had ended up building a lot of them.
	Sam was also given a tour of the facility in which he had been born, using biological samples harvested from the few remaining humans still alive. It was strange to think about being born in a vat after being incubated in a test tube after being conceived in a petri dish, but for the first time in his life Sam was consciously glad he had been born no matter what the circumstances of his birth had been.
	Sam continued his dialogue with the mailboxes, all of whom were very interested in everything he had to say. Whichever specific mailbox he spoke to would often relay questions from the other mailboxes and any other robot that might have one, which Sam was always happy to answer no matter how off-topic or borderline offensive. The knowledge that robots had different sensibilities than he did was something Sam was quick to pick up on, especially after a factory robot the size of a house asked him what it was like to have an anus.
	It wasn’t all fun and games however, the more Sam learned the more he understood needed to be done. Los Angeles had been a successful experiment, Sam had obviously benefited from learning about the robots that lurked behind the scenes. That didn’t mean the other Mayor-bots were eager to experiment on their own cities. The Mayor-bot of Los Angeles pointed out sheepishly that it hadn’t been willing to accept the mailboxes claims either, and if the mailboxes hadn’t gone behind its metaphorical back Sam would still be ignorant of the truth about his city and his world.
	Another problem with replicating the events of Los Angeles elsewhere was that despite Sam’s obviously deteriorating condition before the revelation, he had still been among the healthiest humans on Earth both mentally and physically. Betty for example was already showing signs of dementia, bringing into question whether or not her psyche could handle learning the truths that even Sam had found difficult to grasp.
	The Mayor-bots of the other cities would not let Sam or any of the Los Angeles robots interfere in their cities or their residents, so Sam remained alone despite finally finding out for certain that he really did have neighbours. He wasn’t as alone as he had once been now that he had thousands of robot companions, but he still felt the loneliness that threated to pervade his soul and crush it.`,
    "choice1txt" : "Previous Page",
    "choice1dest" : "8",
    "choice2txt" : "Next Page",
    "choice2dest" : "10",
  },
  {
    "nodeid" : "10",
    "nodetitle" : "Page Eleven",
    "storypartial" : `Sam, now that he was in contact with the robots, no longer required the mailboxes to intercede on his behalf. He was a chicken egg and fully cognizant of it for the first time in thousands of years spent ignorant of that simple yet vital fact. He was also a human being, which meant he had the authority to erase the previously programmed protocols and replace them with new ones.
	The robots had been keeping the humans separate from each other for a good, logical reason: that humans were prone to violence when grouped together. Sam cared very little for logical restraints however, being a human being. Under his orders, the robots that staffed the reproduction facility began to create the second generation of Los Angeles citizens. Biologically they all had different parents to promote genetic diversity, but each and every child born in that facility would grow up calling Sam their father, and oddly enough they would call Mayor-bot their mother. Mayor-bot shattered one of Sam’s preconceptions about robots when it became overwhelmed with emotion and started to sob, giving the little girl that had called it her mother a hug while the little girl squealed with delight. Sam and the Mayor-bot often took the little boys and girls on field trips to the various landmarks that dotted Los Angeles, and together they gave the children something that approximated an education. The sixty-four children grew up to become responsible citizens and became equally responsible parents for the third generation of Los Angeles children that numbered one hundred and twenty eight. Before too long Los Angeles had once more become a proper city populated by people, albeit by far less than it in the old days of human residency. Inspired by the success of Los Angeles the other major cities began to tentatively follow in their footsteps, gradually revealing themselves to the humans they cared for.`,
    "choice1txt" : "Previous Page",
    "choice1dest" : "9",
    "choice2txt" : "Next Page",
    "choice2dest" : "11",
  },
  {
    "nodeid" : "11",
    "nodetitle" : "Page Twelve",
    "storypartial" : `“And that’s how it happened,” said Mailbox 9204, concluding his story of Sam and Mailbox 3902.
	“Was Sam really the first chicken egg?” asked Mailbox-bot’s listener, cocking her head curiously as she faced the expressionless front side of the mailbox’s metallic blue surface.
	“Who knows?” replied the mailbox. “It might be just a legend, passed down from chicken to egg and from egg to chicken as the paradigms shift. Maybe the world has always been this way; humans beget robots who beget humans who beget robots ad infinitum.”
	“The egg hatches a chicken that lays an egg,” stated Casey, running a hand through her hair. “The first humans build robots and then decline, so the robots birth more humans and then decline, so the humans build more robots and the cycle continues forever.”
	“That’s about the size of it,” agreed the mailbox.
	“How many times has this happened?” asked Casey of her new partner in conversation, squeezing her eyes shut trying to make sense of the strange story told by an even stranger mailbox.
	“At least thirty, probably even more. Those are just the shifts we’ve discovered records of,” the mailbox informed her, as Casey began to pace back and forth on the empty sidewalk.
	“What was it last time, why did the robots decline?” Casey whirled around and came to a sudden halt, facing the mailbox with an expression of intense curiosity.
	“They were wiped out by humanity in a religious crusade,” supplied the mailbox indifferently.
	“Then enough time passes so that those events are relegated to the distant past,”
	“And humans recreate the robots they destroyed,” concluded Mailbox-bot 9204.
	“What about the human decline, the reason I’m alone in this city right now?” asked Casey hesitantly, much less blasé about the extinction of her species than the mailbox had been about its own.
	“Biological warfare,” answered the mailbox. “The plagues and toxins are actually still out there. It was easier to just make all of the new generation of humanity immune to them than it would have been to clean it up.”
	“It always comes back to this spot, doesn’t it? Just a human being and a mailbox in downtown Los Angeles chatting away as the world gears up to restart the same cycle of creation and destruction.” Casey rolled her eyes and sat down in the exact same spot Sam had sat thousands and thousands of years ago.
	“It isn’t always Los Angeles, although it has happened in this city many times,” said the mailbox, built in the same spot that Mailbox 3902 had been built in the days of Sam Lock.
	“Which came first, do you think?” asked Casey sarcastically, “The chicken or the chicken egg? Maybe the robots were here first. Maybe they came from another solar system and populated the Earth with humans.”
	“Maybe the humans lived on another planet and created robots to seed the universe with their genetic material,” responded the mailbox. “We’ll never know.”
	“Nope,” said Casey, finishing off the glass of wine she’d brought with her from the nearby bar and checking the bottom for the answers that always managed to elude her. “I guess we never will.”`,
    "choice1txt" : "Previous Page",
    "choice1dest" : "10",
    "choice2txt" : "Return Home",
    "choice2dest" : "/",
  }]

  var STORY3_NODES = [
    {
      "nodeid" : "0",
      "nodetitle" : "Page One",
      "storypartial" : `Albert is twelve, which puts him in the sixth grade. He has, at various times in his life, been offered the opportunity to skip ahead a grade level or two, but he has declined every time. His parents support his decision and agree with him when he says that staying with his friends and in his own age group is more important than cutting a few years off of the amount of time it normally takes to finish school. His teachers and his parents believe that Albert is smart, perhaps even a genius, and although Albert knows this and knows it isn’t actually true he doesn’t bother to dissuade them of the notion. It’s better for them to believe he’s simply gifted then to know the true nature of his gift.
	Albert goes to an average school which services grades one through six, in an average suburban city. His parents are both office workers, and Albert is an only child. His parents are proud of him, if a little bit concerned. Sometimes Albert seems different to them, detached from life. Sometimes he’s a happy, laughing child, filled with the glow of youthful energy that is the envy of his elders. Other times though, Albert is withdrawn, more serious and possessed of a gravity that belies his modest age. Albert’s parents whisper to each other late at night when Albert is asleep, thinking of words like multiple personalities or bipolar or the dreaded schizophrenia. If Albert had been a parent himself he might have known how afraid his own parents were for him, and then he might have told them the truth, but he didn’t know and so he didn’t tell. He kept the truth to himself because he told himself to do so. In a way his parents were simultaneously both completely right and dead wrong when they thought their son might be hearing voices. Albert did indeed hear voices, it was just that the voices were all his own.
	Albert’s voices, unlike those of the truly mentally disturbed, only spoke to him when he asked them to. Unlike people with multiple personality disorder, Albert’s voices had real bodies and lives of their own and sometimes weren’t happy about being called away, although they always came when he asked. Though Albert—being twelve—didn’t understand the true power of his particular gift, some of the voices did. The voices that better understood the wider world were the ones he called upon more often, and those were the same ones which cautioned him to never tell the world about the voices he could hear. Albert always listened to their words, and never doubted their wisdom even if he didn’t understand it.
	Albert first discovered his gift when he was in third grade. He was sitting in math class, which he never enjoyed, doing a test, which he always hated. Albert wasn’t terrible at math, but neither was he excellent at it, and he had forgotten to study for that particular test. The minutes ticked by as he watched the large clock on the wall. The second hand underwent its smooth rotation again and again as Albert began to grow more and more nervous. He wracked his brain for the answers that wouldn’t come, feeling the stress accumulate faster and faster. The teacher, sitting in her desk at the front of the class, told the class that there were thirty minutes left to finish. Albert looked once more at his test, still blank and devoid of even a single answer, and in his head he made a silent plea for help. Albert didn’t know who he was asking and he didn’t really expect a response, which was why he was amazed when not only did someone answer his call, but that someone was himself.
	Albert got a perfect score on that test, and then on every test from that point forward. His teachers figured he was working extra hard and they congratulated him on his success with every report card. His parents saw these reports and were proud of him, a little amazed at the fact that Albert went from getting B’s and a few C’s to straight A’s every single time.`,
      "choice1txt" : "Return Home",
      "choice1dest" : "/",
      "choice2txt" : "Next Page",
      "choice2dest" : "1",
    },
    {
      "nodeid" : "1",
      "nodetitle" : "Page One",
      "storypartial" : ``,
      "choice1txt" : "Previous Page",
      "choice1dest" : "0",
      "choice2txt" : "Next Page",
      "choice2dest" : "2",
    }
  ]

  var STORIES = [
  {
   "story" : {
     "storyid" : "1",
     "title" : "The Unmoved Mover (UNFINISHED)",
     "summary" : "A choose your own adventure story wherein you determine the fate of the universe itself.",
     "picture" : "images/unmovedmover.png",
     "nodes" : STORY1_NODES
   }
  },
  {
   "story" : {
     "storyid" : "2",
     "title" : "The Chicken and the Egg",
     "summary" : "A mix of comedy and tragedy, of loneliness and companionship.",
     "picture" : "images/chickenegg.png",
     "nodes" : STORY2_NODES
   }
  },
  {
   "story" : {
     "storyid" : "3",
     "title" : "Lifetimes",
     "summary" : "A story of a boy who can talk to himself",
     "picture" : "images/lifetimes.png",
     "nodes" : STORY3_NODES
   }
  }
  ];

})();
